import { useEffect, useMemo, useState } from 'react';
import { Activity, BadgeDollarSign, BarChart3, Boxes, BriefcaseBusiness, Building2, CheckCircle2, ClipboardList, DatabaseZap, Factory, MapPinned, PackageCheck, Percent, PhoneCall, Route, Search, ShieldCheck, Target, Truck, UserRoundSearch, UsersRound } from 'lucide-react';
import { businessService } from '../api/api';
import { PageHeader } from '../components/common/Breadcrumbs';
import { Badge, Button, Card, SkeletonCard } from '../components/common/UI';
import { formatDateTime, formatRial, formatRialShort, toFa } from '../utils/ui';
import { showToast } from '../utils/toast';

const tabs = [
  ['overview','فرمان رشد',BarChart3], ['contractors','بانک پیمانکاران',UsersRound], ['commercial','محصول و قیمت',BadgeDollarSign],
  ['targets','اهداف فروش',Target], ['transport','حمل‌ونقل',Truck], ['requests','استعلام‌ها',ClipboardList], ['quality','کیفیت داده',DatabaseZap],
];
const sourceLabels = { project:'پروژه', representative:'نماینده', direct_call:'تماس مستقیم', call:'تماس مستقیم', website:'وب‌سایت', referral:'معرفی', walk_in:'مراجعه حضوری', instagram:'شبکه اجتماعی' };
const requestStatus = { NEW:['جدید','bg-sky-100 text-sky-700'], CONTACTED:['تماس گرفته شد','bg-violet-100 text-violet-700'], QUOTED:['پیش‌فاکتور','bg-amber-100 text-amber-700'], CONVERTED:['تبدیل به فروش','bg-emerald-100 text-emerald-700'], CLOSED:['بسته','bg-slate-100 text-slate-600'] };
const shipmentStatus = { PLANNED:['برنامه‌ریزی','bg-slate-100 text-slate-700'], LOADING:['بارگیری','bg-amber-100 text-amber-700'], SENT:['ارسال‌شده','bg-sky-100 text-sky-700'], DELIVERED:['تحویل‌شده','bg-emerald-100 text-emerald-700'] };

export default function BusinessOperationsPage() {
  const [tab,setTab]=useState('overview'); const [data,setData]=useState(null); const [products,setProducts]=useState([]); const [rules,setRules]=useState([]); const [targets,setTargets]=useState([]); const [contractors,setContractors]=useState([]); const [requests,setRequests]=useState([]); const [shipments,setShipments]=useState([]); const [quality,setQuality]=useState({candidates:[],pending:[]}); const [loading,setLoading]=useState(true); const [search,setSearch]=useState('');
  useEffect(()=>{ Promise.all([businessService.dashboard(),businessService.products(),businessService.priceRules(),businessService.salesTargets(),businessService.contractors(),businessService.purchaseRequests(),businessService.shipments(),businessService.duplicateCandidates()]).then(([a,b,c,d,e,f,g,h])=>{setData(a.data);setProducts(b.data||[]);setRules(c.data||[]);setTargets(d.data||[]);setContractors(e.data||[]);setRequests(f.data||[]);setShipments(g.data||[]);setQuality(h.data||{candidates:[],pending:[]});}).finally(()=>setLoading(false));},[]);
  const filteredContractors=useMemo(()=>contractors.filter(item=>!search||`${item.fullName} ${item.company} ${item.mobile}`.includes(search)),[contractors,search]);
  const updateRequest=async(id,status)=>{const response=await businessService.updatePurchaseRequest(id,{status});setRequests(items=>items.map(item=>item.id===id?{...item,status}:item));showToast(response.message||'وضعیت به‌روزرسانی شد');};
  const queueMerge=async(group)=>{const [target,source]=group.customers;const response=await businessService.createMergeRequest({sourceCustomerId:source.id,targetCustomerId:target.id,reason:`شباهت ${group.matchKey}`,evidence:{confidence:group.confidence}});setQuality(q=>({...q,pending:[response.data,...q.pending]}));showToast(response.message);};
  if(loading)return <div className="grid md:grid-cols-3 gap-4">{[1,2,3,4,5,6].map(i=><SkeletonCard key={i}/>)}</div>;
  return <div className="space-y-6 animate-fade-in">
    <PageHeader title="مرکز عملیات رشد" subtitle="تبدیل پاسخ‌های مدیر به عملیات فروش، پیمانکار، قیمت، حمل و داده" icon={Activity}/>
    <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 px-3.5 py-2.5 rounded-xl text-xs font-black flex items-center gap-2 transition ${tab===id?'bg-slate-950 text-white shadow-lg dark:bg-white dark:text-slate-950':'bg-white dark:bg-surface-800 text-slate-500 border border-slate-200 dark:border-slate-700'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
    {tab==='overview'&&<Overview data={data}/>} 
    {tab==='contractors'&&<Contractors items={filteredContractors} search={search} setSearch={setSearch}/>} 
    {tab==='commercial'&&<Commercial products={products} rules={rules}/>} 
    {tab==='targets'&&<Targets items={targets}/>} 
    {tab==='transport'&&<Transport items={shipments}/>} 
    {tab==='requests'&&<Requests items={requests} update={updateRequest}/>} 
    {tab==='quality'&&<Quality data={quality} queueMerge={queueMerge}/>} 
  </div>;
}

function Overview({data}){const b=data.questionnaireBaseline||{};const maxSeason=Math.max(...(data.seasonal||[]).map(x=>Number(x.sales)||0),1);const maxProvince=Math.max(...(data.geography||[]).map(x=>Number(x.count)||0),1);return <>
  <Card className="p-6 bg-slate-950 text-white border-0 overflow-hidden relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_10%,rgba(14,165,233,.32),transparent_30%),radial-gradient(circle_at_90%_90%,rgba(124,58,237,.32),transparent_34%)]"/><div className="relative grid lg:grid-cols-[1.25fr_1fr] gap-6 items-center"><div><div className="text-xs text-sky-200 font-black">نتیجه پرسشنامه ۱۳۸ سؤالی</div><h2 className="text-2xl font-black mt-2">جذب سرنخ و دید کامل روی پیمانکار و پروژه، اولویت شماره یک</h2><p className="text-sm text-slate-300 leading-7 mt-3">فروش شرکت پروژه‌محور است؛ مرکز عملیات، منبع سرنخ را تا فاکتور و مزیت حمل دنبال می‌کند و اطلاعات مشتری نهایی نماینده را از دسترس خارج نمی‌گذارد.</p></div><div className="grid grid-cols-3 gap-3">{[[b.projectShare,'پروژه'],[b.representativeShare,'نماینده'],[b.directShare,'مستقیم']].map(([v,l])=><div key={l} className="rounded-2xl bg-white/10 border border-white/10 p-4 text-center"><div className="text-2xl font-black">٪{toFa(v)}</div><div className="text-[10px] text-slate-300 mt-1">{l}</div></div>)}</div></div></Card>
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-4"><Kpi icon={UsersRound} value={data.kpis.customers} label="مشتری ثبت‌شده" note={`${toFa(data.kpis.activeCustomers)} فعال`}/><Kpi icon={Building2} value={data.kpis.contractors} label="پیمانکار شناسایی‌شده" note={`${toFa(data.kpis.projects)} پروژه`}/><Kpi icon={ClipboardList} value={data.kpis.openRequests} label="استعلام باز" note="نیازمند پیگیری"/><Kpi icon={Percent} value={`${toFa(data.kpis.cashShare)}٪`} label="سهم فروش نقدی" note="هدف پرسشنامه: افزایش"/></div>
  <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-5"><Card className="overflow-hidden"><Section title="کارایی منابع سرنخ" subtitle="از اولین تماس تا برد فروش"/><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-800 text-slate-400"><tr><Th>منبع</Th><Th>سرنخ</Th><Th>برد</Th><Th>نرخ تبدیل</Th><Th>ارزش قیف</Th></tr></thead><tbody>{data.sourcePerformance.map(row=><tr key={row.source} className="border-t border-slate-100 dark:border-slate-800"><Td strong>{sourceLabels[row.source]||row.source}</Td><Td>{toFa(row.total)}</Td><Td>{toFa(row.won)}</Td><Td><span className="text-emerald-600 font-black">٪{toFa(row.conversionRate)}</span></Td><Td>{formatRialShort(row.pipelineValue)} ریال</Td></tr>)}</tbody></table></div></Card>
  <Card className="p-5"><h3 className="font-black text-sm text-slate-900 dark:text-white">پراکندگی مشتریان</h3><p className="text-[11px] text-slate-400 mt-1">تمرکز اولیه کرمان و هرمزگان</p><div className="space-y-3 mt-5">{data.geography.slice(0,6).map(row=><div key={row.province}><div className="flex justify-between text-xs"><span className="font-bold">{row.province}</span><span className="text-slate-400">{toFa(row.count)}</span></div><div className="h-2 bg-slate-100 dark:bg-slate-800 rounded-full mt-1.5 overflow-hidden"><div className="h-full bg-gradient-to-l from-sky-500 to-violet-500 rounded-full" style={{width:`${Math.max(8,row.count/maxProvince*100)}%`}}/></div></div>)}</div></Card></div>
  <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-black text-sm">فصل فروش</h3><p className="text-[11px] text-slate-400 mt-1">مبنای برنامه‌ریزی کمپین و هدف‌گذاری دوره اوج</p></div><Badge color="bg-amber-100 text-amber-700">اوج: {b.peakSeason}</Badge></div><div className="h-44 flex items-end gap-2 mt-6">{data.seasonal.map((row,index)=><div key={row.month} className="flex-1 h-full flex flex-col justify-end items-center gap-2"><div title={`${formatRialShort(row.sales)} ریال`} className={`w-full max-w-8 rounded-t-lg ${index>=3&&index<=5?'bg-gradient-to-t from-amber-500 to-orange-300':'bg-gradient-to-t from-sky-600 to-sky-300'}`} style={{height:`${Math.max(7,Number(row.sales)/maxSeason*100)}%`}}/><span className="text-[9px] text-slate-400">{toFa(row.month)}</span></div>)}</div></Card>
  </>}

function Contractors({items,search,setSearch}){return <><Card className="p-5 bg-gradient-to-l from-sky-50 to-white dark:from-sky-950/20 dark:to-surface-800"><div className="grid lg:grid-cols-[1fr_360px] gap-5 items-center"><div><h2 className="text-xl font-black">بانک ۳۶۰ درجه پیمانکاران</h2><p className="text-sm text-slate-500 mt-2 leading-7">هر پیمانکار با خرید، پروژه، نماینده معرف، درخواست‌ها و وضعیت وفاداری در یک پرونده دیده می‌شود.</p></div><div className="relative"><Search className="absolute right-3 top-3.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام، شرکت یا موبایل..." className="w-full pr-10 pl-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-surface-900 text-sm outline-none"/></div></div></Card><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-800 text-slate-400"><tr><Th>پیمانکار</Th><Th>شهر</Th><Th>خرید تجمعی</Th><Th>فاکتور</Th><Th>پروژه شبکه</Th><Th>سطح</Th><Th>وضعیت</Th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><Td strong><div>{item.fullName}</div><div className="text-[10px] text-slate-400 mt-1">{item.company} · {item.mobile}</div></Td><Td>{item.city||'—'}</Td><Td>{formatRialShort(item.totalPurchase)} ریال</Td><Td>{toFa(item._count?.invoices||item.invoicesCount||0)}</Td><Td>{toFa(item._count?.networkRegistrations||0)}</Td><Td><Badge color="bg-violet-100 text-violet-700">{item.tier?.title||'پایه'}</Badge></Td><Td><Badge color={item.status==='IN_RISK'?'bg-red-100 text-red-700':'bg-emerald-100 text-emerald-700'}>{item.status==='IN_RISK'?'در معرض ریزش':'فعال'}</Badge></Td></tr>)}</tbody></table></div></Card></>}

function Commercial({products,rules}){const cats={CEILING_EPS:'یونولیت سقفی',WALL_EPS:'یونولیت دیواری',THREED_PANEL:'پنل سه‌بعدی',PACKAGING:'بسته‌بندی'};return <><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{products.map(product=><Card key={product.id} className="p-5"><div className="w-11 h-11 rounded-2xl bg-sky-100 text-sky-700 flex items-center justify-center"><Boxes className="w-5 h-5"/></div><h3 className="font-black text-sm mt-4">{product.title}</h3><div className="text-[11px] text-slate-400 mt-1">{cats[product.category]||product.category} · دانسیته {toFa(product.densityMin)} تا {toFa(product.densityMax)}</div><div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800"><b className="text-violet-600">{formatRial(product.basePrice)}</b><span className="text-[9px] text-slate-400 mr-1">{product.priceUnit}</span></div></Card>)}</div><Card className="overflow-hidden"><Section title="ماتریس قیمت و تخفیف" subtitle="قواعد نقدی، حجمی، پروژه‌ای، نمایندگی و حمل"/><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-800 text-slate-400"><tr><Th>قانون</Th><Th>نوع</Th><Th>حداقل خرید</Th><Th>درصد</Th><Th>سقف</Th><Th>کنترل</Th></tr></thead><tbody>{rules.map(rule=><tr key={rule.id} className="border-t border-slate-100 dark:border-slate-800"><Td strong>{rule.title}</Td><Td>{rule.ruleType}</Td><Td>{formatRialShort(rule.minAmount)} ریال</Td><Td>٪{toFa(rule.discountPercent)}</Td><Td>{rule.maxDiscountRial?`${formatRialShort(rule.maxDiscountRial)} ریال`:'—'}</Td><Td><Badge color={rule.approvalRequired?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}>{rule.approvalRequired?'نیازمند تأیید':'خودکار'}</Badge></Td></tr>)}</tbody></table></div></Card></>}

function Targets({items}){return <div className="grid lg:grid-cols-3 gap-5">{items.map(item=>{const pct=Math.min(100,Math.round(Number(item.achievedAmount)/Math.max(1,Number(item.targetAmount))*100));return <Card key={item.id} className="p-5"><div className="flex justify-between"><div><div className="text-[10px] text-slate-400">{item.period}</div><h3 className="font-black mt-1">{item.scopeLabel}</h3></div><div className="w-11 h-11 rounded-2xl bg-violet-100 text-violet-700 flex items-center justify-center"><Target className="w-5 h-5"/></div></div><div className="text-2xl font-black mt-5">{formatRialShort(item.achievedAmount)} <span className="text-xs text-slate-400">از {formatRialShort(item.targetAmount)} ریال</span></div><div className="h-2 bg-slate-100 dark:bg-slate-800 rounded-full mt-3 overflow-hidden"><div className="h-full bg-gradient-to-l from-violet-600 to-sky-500" style={{width:`${pct}%`}}/></div><div className="grid grid-cols-3 gap-2 mt-4"><Mini label="تحقق" value={`٪${toFa(pct)}`}/><Mini label="فروش نقدی" value={`٪${toFa(item.achievedCashShare)}`}/><Mini label="پروژه" value={`${toFa(item.achievedProjects)}/${toFa(item.targetProjects)}`}/></div></Card>})}</div>}

function Transport({items}){const total=items.reduce((s,x)=>s+Number(x.transportCost||0),0),benefit=items.reduce((s,x)=>s+Number(x.benefitAmount||0),0);return <><div className="grid sm:grid-cols-3 gap-4"><Kpi icon={Route} value={`${formatRialShort(total)} ریال`} label="هزینه حمل ثبت‌شده" note="قابل حسابرسی"/><Kpi icon={Percent} value={`${formatRialShort(benefit)} ریال`} label="یارانه باشگاه" note="تخفیف و امتیاز"/><Kpi icon={ShieldCheck} value={items.filter(x=>x.requiresApproval).length} label="نیازمند تأیید" note="کنترل حاشیه سود"/></div><Card className="overflow-hidden"><Section title="دفتر ارسال و مزایای حمل" subtitle="مبلغ خرید، سطح مشتری و امتیاز مصرفی در یک رکورد"/><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-800 text-slate-400"><tr><Th>رهگیری</Th><Th>مشتری</Th><Th>مسیر</Th><Th>کرایه</Th><Th>مزیت</Th><Th>امتیاز</Th><Th>وضعیت</Th></tr></thead><tbody>{items.map(item=>{const st=shipmentStatus[item.status]||shipmentStatus.PLANNED;return <tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><Td strong>{item.trackingCode}</Td><Td>{item.customer?.company||item.customer?.fullName||'—'}</Td><Td>{item.origin} ← {item.destination}</Td><Td>{formatRial(item.transportCost)} ریال</Td><Td>{formatRial(item.benefitAmount)} ریال</Td><Td>{toFa(item.pointsUsed)}</Td><Td><Badge color={st[1]}>{st[0]}</Badge>{item.requiresApproval&&<div className="text-[9px] text-amber-600 mt-1">تأیید مدیر</div>}</Td></tr>})}</tbody></table></div></Card></>}

function Requests({items,update}){return <><Card className="p-5 bg-gradient-to-l from-violet-50 to-white dark:from-violet-950/20 dark:to-surface-800"><div className="flex gap-4 items-center"><div className="w-12 h-12 rounded-2xl bg-violet-600 text-white flex items-center justify-center"><PhoneCall className="w-5 h-5"/></div><div><h2 className="font-black">استعلام به‌جای فروشگاه اینترنتی</h2><p className="text-xs text-slate-500 mt-1">مشتری درخواست را ثبت می‌کند و کارشناس فروش همان روز تماس می‌گیرد.</p></div></div></Card><div className="grid lg:grid-cols-2 gap-4">{items.map(item=>{const st=requestStatus[item.status]||requestStatus.NEW;return <Card key={item.id} className="p-5"><div className="flex justify-between gap-3"><div><div className="text-[10px] text-slate-400">{item.trackingCode} · {formatDateTime(item.createdAt)}</div><h3 className="font-black mt-1">{item.productTitle}</h3><div className="text-xs text-slate-500 mt-1">{item.customer?.company} · {item.customer?.fullName}</div></div><Badge color={st[1]}>{st[0]}</Badge></div><div className="grid grid-cols-3 gap-2 mt-4"><Mini label="مقدار" value={`${toFa(item.quantity)} ${item.unit||''}`}/><Mini label="پروژه" value={item.projectName||'—'}/><Mini label="شهر" value={item.city||'—'}/></div>{item.description&&<p className="text-xs text-slate-500 bg-slate-50 dark:bg-slate-800 rounded-xl p-3 mt-3">{item.description}</p>}<div className="flex gap-2 mt-4">{item.status==='NEW'&&<Button size="sm" icon={PhoneCall} onClick={()=>update(item.id,'CONTACTED')}>ثبت تماس</Button>}{item.status==='CONTACTED'&&<Button size="sm" icon={ClipboardList} onClick={()=>update(item.id,'QUOTED')}>ثبت پیش‌فاکتور</Button>}{item.status==='QUOTED'&&<Button size="sm" variant="success" icon={CheckCircle2} onClick={()=>update(item.id,'CONVERTED')}>تبدیل به فروش</Button>}</div></Card>})}</div></>}

function Quality({data,queueMerge}){return <><div className="grid sm:grid-cols-3 gap-4"><Kpi icon={UserRoundSearch} value={data.candidates.length} label="گروه مشابه" note="نیازمند بررسی انسانی"/><Kpi icon={ClipboardList} value={data.pending.length} label="در صف ادغام" note="بدون حذف خودکار"/><Kpi icon={ShieldCheck} value="۱۰۰٪" label="ادغام ایمن" note="پس از تأیید مدیر"/></div><div className="grid lg:grid-cols-2 gap-4">{data.candidates.map(group=><Card key={group.matchKey} className="p-5"><div className="flex justify-between"><div><h3 className="font-black">رکوردهای مشابه</h3><div className="text-[10px] text-slate-400 mt-1">مبنای تشخیص: {group.matchKey}</div></div><Badge color={group.confidence>=80?'bg-amber-100 text-amber-700':'bg-sky-100 text-sky-700'}>اطمینان ٪{toFa(group.confidence)}</Badge></div><div className="space-y-2 mt-4">{group.customers.map(item=><div key={item.id} className="rounded-xl bg-slate-50 dark:bg-slate-800 p-3 flex justify-between gap-3"><div><div className="text-xs font-black">{item.fullName}</div><div className="text-[10px] text-slate-400 mt-1">{item.company} · {item.mobile}</div></div><div className="text-[10px] text-slate-500">{formatRialShort(item.totalPurchase)} ریال</div></div>)}</div><Button className="mt-4" variant="secondary" icon={DatabaseZap} onClick={()=>queueMerge(group)}>ارسال به صف ادغام</Button></Card>)}</div></>}

function Kpi({icon:Icon,value,label,note}){return <Card className="p-5"><div className="w-10 h-10 rounded-2xl bg-sky-100 dark:bg-sky-900/30 text-sky-700 dark:text-sky-300 flex items-center justify-center"><Icon className="w-4.5 h-4.5"/></div><div className="text-2xl font-black mt-4 text-slate-900 dark:text-white">{typeof value==='number'?toFa(value):value}</div><div className="text-xs font-bold mt-1">{label}</div><div className="text-[10px] text-slate-400 mt-1">{note}</div></Card>}
function Section({title,subtitle}){return <div className="p-5 border-b border-slate-100 dark:border-slate-800"><h3 className="font-black text-sm">{title}</h3><p className="text-[11px] text-slate-400 mt-1">{subtitle}</p></div>}
function Mini({label,value}){return <div className="rounded-xl bg-slate-50 dark:bg-slate-800 p-2.5 min-w-0"><div className="text-[9px] text-slate-400">{label}</div><div className="text-[11px] font-black mt-1 truncate">{value}</div></div>}
function Th({children}){return <th className="text-right font-bold p-3 whitespace-nowrap">{children}</th>}
function Td({children,strong}){return <td className={`p-3 whitespace-nowrap ${strong?'font-black text-slate-900 dark:text-white':'text-slate-600 dark:text-slate-300'}`}>{children}</td>}
