import { useEffect, useState } from 'react';
import { Building2, BadgeCheck, MapPinned, FolderKanban, Percent, CheckCircle2, XCircle, ExternalLink } from 'lucide-react';
import { representativeService } from '../api/api';
import { PageHeader } from '../components/common/Breadcrumbs';
import { Avatar, Badge, Button, Card, SkeletonCard } from '../components/common/UI';
import { formatRial, toFa } from '../utils/ui';
import { showToast } from '../utils/toast';

const gradeLabel = { C:'C', B:'B', A:'A', EXCELLENT:'ممتاز' };
const statusMap = { PENDING:['در انتظار بررسی','bg-amber-100 text-amber-700'], APPROVED:['تأییدشده','bg-emerald-100 text-emerald-700'], REJECTED:['ردشده','bg-red-100 text-red-700'] };

export default function RepresentativeNetworkPage() {
  const [representatives, setRepresentatives] = useState([]);
  const [registrations, setRegistrations] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([representativeService.list(), representativeService.registrations()]).then(([a,b]) => { setRepresentatives(a.data||[]); setRegistrations(b.data||[]); }).finally(() => setLoading(false)); }, []);
  const review = async (id, status) => { try { const response=await representativeService.reviewRegistration(id,{status,discountPercent:7.5}); setRegistrations(items => items.map(item => item.id===id ? {...item,status,pointsAwarded:status==='APPROVED'?300:0,discountPercent:status==='APPROVED'?7.5:0}:item)); showToast(response.message); } catch(error) { showToast(error.message,'error'); } };
  if (loading) return <div className="grid md:grid-cols-4 gap-4">{[1,2,3,4].map(i=><SkeletonCard key={i}/>)}</div>;
  const gradeCounts = ['C','B','A','EXCELLENT'].map(grade => ({ grade, count: representatives.filter(item=>item.grade===grade).length }));
  return <div className="space-y-6 animate-fade-in">
    <PageHeader title="کنترل شبکه نمایندگان" subtitle="سطح‌بندی C تا ممتاز، ثبت اجباری پروژه و کنترل تخفیف نمایندگی" icon={Building2} actions={<Button variant="secondary" icon={ExternalLink} onClick={() => window.open('/representative','_blank')}>پیش‌نمایش پرتال نماینده</Button>} />
    <Card className="p-6 bg-slate-950 text-white border-0 overflow-hidden relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(14,165,233,.28),transparent_30%),radial-gradient(circle_at_85%_80%,rgba(16,185,129,.22),transparent_32%)]"/><div className="relative grid lg:grid-cols-[1fr_auto] gap-6 items-center"><div><div className="text-xs text-sky-200 font-bold">قانون شبکه فروش</div><h2 className="text-2xl font-black mt-2">تخفیف نمایندگی فقط پس از ثبت مشتری نهایی و پروژه</h2><p className="text-sm text-slate-300 leading-7 mt-2">هر درخواست با نام پیمانکار، موبایل، پروژه، شهر و حجم برآوردی وارد صف تأیید می‌شود؛ تأیید مدیر هم‌زمان تخفیف و ۳۰۰ امتیاز معرفی پروژه را فعال می‌کند.</p></div><div className="grid grid-cols-2 gap-3"><HeroStat value={representatives.length} label="نماینده فعال"/><HeroStat value={registrations.length} label="پروژه ثبت‌شده"/></div></div></Card>
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{gradeCounts.map((item,index)=><Card key={item.grade} className="p-5"><div className={`w-11 h-11 rounded-2xl flex items-center justify-center font-black ${['bg-slate-100 text-slate-600','bg-sky-100 text-sky-700','bg-amber-100 text-amber-700','bg-violet-100 text-violet-700'][index]}`}>{gradeLabel[item.grade]}</div><div className="text-2xl font-black text-slate-900 dark:text-white mt-4">{toFa(item.count)}</div><div className="text-xs text-slate-500 mt-1">نماینده سطح {gradeLabel[item.grade]}</div></Card>)}</div>
    <div className="grid xl:grid-cols-2 gap-5">
      <Card className="overflow-hidden"><div className="p-5 border-b border-slate-100 dark:border-slate-800"><h3 className="font-black text-slate-900 dark:text-white">شبکه تحت کنترل</h3></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{representatives.map(rep=><div key={rep.id} className="p-4 flex items-center gap-3"><Avatar name={rep.customer.fullName}/><div className="flex-1 min-w-0"><div className="font-black text-sm text-slate-900 dark:text-white truncate">{rep.customer.company}</div><div className="text-[11px] text-slate-400 mt-1 flex items-center gap-2"><MapPinned className="w-3 h-3"/>{rep.region} · {rep.code}</div></div><div className="text-left"><Badge color="bg-violet-100 text-violet-700">سطح {gradeLabel[rep.grade]}</Badge><div className="text-[11px] text-slate-400 mt-2">{toFa(rep.discountRate)}٪ تخفیف</div></div></div>)}</div></Card>
      <Card className="overflow-hidden"><div className="p-5 border-b border-slate-100 dark:border-slate-800"><h3 className="font-black text-slate-900 dark:text-white">صف بررسی پروژه و پیمانکار</h3></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{registrations.map(item=>{const status=statusMap[item.status]||statusMap.PENDING;return <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-black text-sm text-slate-900 dark:text-white">{item.project?.title}</div><div className="text-xs text-slate-500 mt-1">{item.contractorName} · {item.contractorCompany}</div></div><Badge color={status[1]}>{status[0]}</Badge></div><div className="grid grid-cols-3 gap-2 mt-3 text-[11px]"><Info icon={MapPinned} label="شهر" value={item.city}/><Info icon={FolderKanban} label="حجم" value={`${formatRial(item.estimatedVolume)} ریال`}/><Info icon={Percent} label="تخفیف" value={`${toFa(item.discountPercent)}٪`}/></div>{item.status==='PENDING'&&<div className="flex gap-2 mt-3"><Button size="sm" variant="success" icon={CheckCircle2} onClick={()=>review(item.id,'APPROVED')}>تأیید و امتیاز</Button><Button size="sm" variant="danger" icon={XCircle} onClick={()=>review(item.id,'REJECTED')}>رد</Button></div>}{item.status==='APPROVED'&&<div className="mt-3 text-xs font-bold text-emerald-600 flex items-center gap-1"><BadgeCheck className="w-4 h-4"/>{toFa(item.pointsAwarded)} امتیاز معرفی پروژه ثبت شد</div>}</div>;})}</div></Card>
    </div>
  </div>;
}
function HeroStat({value,label}){return <div className="rounded-2xl bg-white/10 border border-white/10 p-4 min-w-32"><div className="text-2xl font-black">{toFa(value)}</div><div className="text-[11px] text-slate-300 mt-1">{label}</div></div>}
function Info({icon:Icon,label,value}){return <div className="rounded-xl bg-slate-50 dark:bg-slate-800 p-2"><div className="text-slate-400 flex items-center gap-1"><Icon className="w-3 h-3"/>{label}</div><div className="font-bold text-slate-700 dark:text-slate-200 mt-1 truncate">{value}</div></div>}
