import { useEffect, useState } from 'react';
import { Building2, Crown, Percent, FolderPlus, BadgeCheck, ArrowRight, MapPin, Phone } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { representativeService } from '../api/api';
import { Badge, Button, Card, SkeletonCard } from '../components/common/UI';
import { showToast } from '../utils/toast';
import { formatRial, toFa } from '../utils/ui';

const statusMap={PENDING:['در انتظار بررسی','bg-amber-100 text-amber-700'],APPROVED:['تأیید و تخفیف فعال','bg-emerald-100 text-emerald-700'],REJECTED:['نیازمند اصلاح','bg-red-100 text-red-700']};

export default function RepresentativePortalPage(){
  const navigate=useNavigate();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[showForm,setShowForm]=useState(false);const[form,setForm]=useState({contractorName:'',contractorMobile:'',contractorCompany:'',projectTitle:'',city:'',estimatedVolume:''});
  useEffect(()=>{representativeService.portal().then(r=>setData(r.data)).finally(()=>setLoading(false))},[]);
  const submit=async(e)=>{e.preventDefault();try{const r=await representativeService.registerProject(form);setData(prev=>({...prev,registrations:[r.data,...(prev.registrations||[])]}));setShowForm(false);showToast(r.message)}catch(error){showToast(error.message,'error')}};
  if(loading)return <div className="min-h-screen bg-slate-50 dark:bg-surface-900 p-6"><SkeletonCard className="max-w-5xl mx-auto"/></div>;
  return <div className="min-h-screen bg-slate-50 dark:bg-surface-900" dir="rtl"><header className="h-16 bg-white dark:bg-surface-800 border-b border-slate-200 dark:border-slate-800 px-4 flex items-center"><div className="w-full max-w-6xl mx-auto flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-brand-500 to-violet-700 text-white flex items-center justify-center"><Building2 className="w-5 h-5"/></div><div><b className="text-slate-900 dark:text-white">پرتال نمایندگان پویا</b><div className="text-[10px] text-slate-400">ثبت مشتری نهایی و پروژه</div></div></div><button onClick={()=>navigate('/dashboard')} className="text-xs font-bold text-slate-500 flex items-center gap-1"><ArrowRight className="w-4 h-4"/>بازگشت به پنل</button></div></header>
    <main className="max-w-6xl mx-auto p-4 sm:p-6 space-y-5"><section className="rounded-3xl bg-slate-950 text-white p-6 sm:p-8 overflow-hidden relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_20%,rgba(14,165,233,.34),transparent_30%),radial-gradient(circle_at_90%_80%,rgba(124,58,237,.32),transparent_32%)]"/><div className="relative flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6"><div><div className="text-xs text-sky-200">خوش آمدید، {data?.customer?.fullName}</div><h1 className="text-2xl sm:text-3xl font-black mt-2">{data?.customer?.company}</h1><div className="flex flex-wrap gap-2 mt-4"><Badge color="bg-white/10 text-white">کد {data?.code}</Badge><Badge color="bg-white/10 text-white"><MapPin className="w-3 h-3"/>{data?.region}</Badge></div></div><div className="grid grid-cols-3 gap-3 w-full lg:w-auto"><Hero icon={Crown} value={data?.grade==='EXCELLENT'?'ممتاز':data?.grade} label="سطح نماینده"/><Hero icon={Percent} value={`${toFa(data?.discountRate)}٪`} label="تخفیف پایه"/><Hero icon={FolderPlus} value={toFa(data?.registrations?.length||0)} label="پروژه ثبت‌شده"/></div></div></section>
      <div className="grid lg:grid-cols-[1fr_320px] gap-5"><Card className="overflow-hidden"><div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between"><div><h2 className="font-black text-slate-900 dark:text-white">پروژه‌های معرفی‌شده</h2><p className="text-xs text-slate-400 mt-1">وضعیت بررسی تخفیف و پاداش معرفی</p></div><Button icon={FolderPlus} onClick={()=>setShowForm(true)}>ثبت پروژه جدید</Button></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{(data?.registrations||[]).map(item=>{const s=statusMap[item.status]||statusMap.PENDING;return <div key={item.id} className="p-4 flex items-start justify-between gap-3"><div><div className="font-black text-sm text-slate-900 dark:text-white">{item.project?.title}</div><div className="text-xs text-slate-500 mt-1">{item.contractorName} · {item.contractorCompany}</div><div className="text-[11px] text-slate-400 mt-2">حجم برآوردی: {formatRial(item.estimatedVolume)} ریال</div></div><div className="text-left"><Badge color={s[1]}>{s[0]}</Badge>{item.pointsAwarded>0&&<div className="text-xs font-bold text-emerald-600 mt-2">+{toFa(item.pointsAwarded)} امتیاز</div>}</div></div>})}</div></Card><div className="space-y-4"><Card className="p-5"><BadgeCheck className="w-8 h-8 text-emerald-500"/><h3 className="font-black text-slate-900 dark:text-white mt-4">شرط فعال‌شدن تخفیف</h3><p className="text-xs text-slate-500 leading-6 mt-2">نام پیمانکار، شماره موبایل، نام پروژه، شهر و حجم برآوردی را کامل ثبت کنید. پس از تأیید مدیر، تخفیف و امتیاز معرفی فعال می‌شود.</p></Card><Card className="p-5"><div className="text-xs text-slate-400">امتیاز طول عمر</div><div className="text-2xl font-black text-slate-900 dark:text-white mt-2">{toFa(data?.customer?.lifetimePoints||0)}</div><div className="text-xs text-violet-600 font-bold mt-2">سطح {data?.customer?.tier?.title}</div></Card></div></div>
    </main>
    {showForm&&<div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-sm flex items-center justify-center p-4" onClick={()=>setShowForm(false)}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="w-full max-w-2xl bg-white dark:bg-surface-800 rounded-2xl p-6"><h3 className="font-black text-lg text-slate-900 dark:text-white">ثبت پیمانکار و پروژه</h3><div className="grid sm:grid-cols-2 gap-3 mt-5"><Field label="نام پیمانکار" value={form.contractorName} onChange={v=>setForm({...form,contractorName:v})}/><Field label="موبایل پیمانکار" value={form.contractorMobile} onChange={v=>setForm({...form,contractorMobile:v})} icon={Phone}/><Field label="شرکت پیمانکار" value={form.contractorCompany} onChange={v=>setForm({...form,contractorCompany:v})}/><Field label="نام پروژه" value={form.projectTitle} onChange={v=>setForm({...form,projectTitle:v})}/><Field label="شهر" value={form.city} onChange={v=>setForm({...form,city:v})}/><Field label="حجم برآوردی (ریال)" value={form.estimatedVolume} onChange={v=>setForm({...form,estimatedVolume:v})} type="number"/></div><div className="flex justify-end gap-2 mt-5"><Button type="button" variant="secondary" onClick={()=>setShowForm(false)}>انصراف</Button><Button type="submit">ارسال برای بررسی</Button></div></form></div>}
  </div>}
function Hero({icon:Icon,value,label}){return <div className="rounded-2xl bg-white/10 border border-white/10 p-3 min-w-0 sm:min-w-28"><Icon className="w-4 h-4 text-sky-300"/><div className="font-black text-xl mt-2 truncate">{value}</div><div className="text-[10px] text-slate-300 mt-1">{label}</div></div>}
function Field({label,value,onChange,type='text',icon:Icon}){return <label className="text-xs font-bold text-slate-600 dark:text-slate-300">{label}<div className="relative mt-2">{Icon&&<Icon className="absolute right-3 top-3.5 w-4 h-4 text-slate-400"/>}<input required value={value} type={type} onChange={e=>onChange(e.target.value)} className={`w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent p-3 outline-none focus:border-brand-500 ${Icon?'pr-10':''}`}/></div></label>}
